server:
  port: 8080
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/udbs?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&allowMultiQueries=true&useSSL=true&verifyServerCertificate=false
      username: udbs
      password: udbspass
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 200
      initialSize: 10
      maxWait: 60000
      minIdle: 20
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: "select 1"
      testWhileIdle: true
      maxOpenPreparedStatements: 20
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      useGlobalDataSourceStat: true
  http:
    multipart:
      max-file-size: 10MB
essay:
  pictureLocation: D:\udbs\picture\
  requestUrl: http://localhost:8880/picture/
operation:
  sourceLocation: D:\udbs\sources\
  tmpUrl: D:\udbs\tmp\sources\
  requestUrl: http://localhost:8880/sources/
flyway:
  out-of-order: true


